name: generate animation

on:
  schedule:
    - cron: "0 0 * * *" 
    - cron: "0 12 * * *"
  # allows to manually run the job at any time
  workflow_dispatch:
  
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  generate:
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:           A preset of color, one of [github, github-dark, github-light]
          #  - color_snake:       Color of the snake
          #  - color_dots:        Coma separated list of dots color.
          #                       The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                       Exactly 5 colors are expected.
          #  - color_background:  Color of the background (for gif only)
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add dist/github-snake*.svg dist/ocean.gif
          git commit -m "docs: update contribution snake animation"
          git push -u origin main
